---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Add PHP PPA repository
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install required packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - php{{ php_version }}
  - nginx
  - mysql-server
  - python{{ python_version }}-mysqldb
  - python{{ python_version }}


- name: Install php extensions
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - php{{ php_version }}-mysql
  - php{{ php_version }}-gd
  - php{{ php_version }}-ssh2
  - php{{ php_version }}-cli
  - php{{ php_version }}-fpm
  - php{{ php_version }}-json
  - php{{ php_version }}-opcache
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-xml 
  - php{{ php_version }}-gd
  - php{{ php_version }}-curl

