---

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: yes  
  listen: "Enables new site"

- name: restart php
  ansible.builtin.service:
    name: php7.2-fpm
    state: restarted
  become: true

