---
  
# Wordpress database settings 
wp_mysql_db: wordpress
wp_mysql_user: wordpress
wp_mysql_password: qwerjgxgcjxxcxgxjcgxjty

# PHP version
php_version: 7.2

# Python version
python_version: 3

# server settings
http_host: "10.100.198.201"
http_conf: "10.100.198.201.conf"
http_port: "80"
